name: ui_repository
description: flutter login ui app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  flutter_svg: ^1.0.0
  firebase_core:
  cloud_firestore:
  geolocator:
  google_maps_flutter:
  google_maps_flutter_web:
  permission_handler:
  firebase_auth:
  http:
  google_sign_in:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets 경로 지정
  assets:
    - assets/images/logo.PNG
    - assets/images/google.PNG