name: ui_repository
description: flutter login ui app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  #외부 라이브러리 https://pub.dev/packages/flutter_svg
  flutter_svg: ^1.0.0
  firebase_core: ^2.2.0
  cloud_firestore:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  # assets 경로 지정
  assets:
    - assets/images/logo.PNG